### ISSUE TITLE
package not puplished to npm?

### ISSUE THREAD

**Issue by kjetilhp** [gremo/nest-winston#1]
npm i --save nest-winston winston

> npm ERR! No valid versions available for nest-winston

**Comment by gremo** [comment]
Yes, I didn't publish this package to NPM. I consider it just an "experiment" for now, I've a lot of ideas about improving it.

**Comment by webernir** [comment]
too bad. 
would like to use it :(

**Comment by gremo** [comment]
Well, I'll publish It tomorrow. Thanks and feel free to contribute!

**Comment by gremo** [comment]
I've got an error while publishing to npm. Now it shows "1 packages" but list is empty, it's "stuck" and I can't publish or unblish. I've contacted the support team.

**Comment by gremo** [comment]
This library is now on npm! We are starting from v1.0.1 because of that problem with npm! Cheers 👍
