### ISSUE TITLE
Adding new logger transport depending on environment

### ISSUE THREAD

**Issue by rainercedric23** [gremo/nest-winston#108]
I am implementing a logger module using `nest-winston` but I don't know how to implement a  a new logger depending on environment cleanly, here's my `LoggerModule`:

```
import { Module } from "@nestjs/common";
import { WinstonModule, utilities } from 'nest-winston';
import * as winston from 'winston';
import configuration from "../config/configuration";
// Create a method to transform stacktrace error to Object
const errorStackFormat = winston.format(info => {
  if (info instanceof Error) {
    return Object.assign({}, info, {
      stack: info.stack,
      message: info.message
    })
  }
  return info
})

@Module({
  imports: [
    WinstonModule.forRootAsync({
      useFactory: () => ({
        level: "info",
        format: winston.format.combine(errorStackFormat()),
        defaultMeta: { service: "api" },
        transports: [
            new winston.transports.File({ filename: configuration.errLogPath + "/error.log", level: "error" }),
            new winston.transports.File({ filename: configuration.appLogPath + "/combined.log", level: 'info' }),
            new winston.transports.Console({
              format: winston.format.combine(
                winston.format.timestamp(),
                utilities.format.nestLike()
              )
            }),
        ],
      }),
      inject: [],
    }),
  ],
})

export class LoggerModule {}

```

**Comment by gremo** [comment]
Check the async configuration: you can inject your configuration service (where I imagine you store the current environment) and then... simply return the appropriate options based on that.

**Comment by gremo** [comment]
Sorry... didn't see that you are actually using the async configuration. Just return different options based on the environment, i your factory function then :)

**Comment by gremo** [comment]
Did you solved?

**Comment by rainercedric23** [comment]
Yes I've solved it by using ConfigModule like this:

`import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { User } from '../user/user.entity';
import { ConfigService, ConfigModule } from '@nestjs/config';

@Module({
    imports: [
        WinstonModule.forRootAsync({
            imports: [ConfigModule],
            inject: [ConfigService],
            useFactory: (configService: ConfigService) => (
                 configService.get('logger.config')
            ),
        }),
    ],
})
export class LoggerModule {}
`

**Comment by gremo** [comment]
@rainercedric23 good!

**Comment by cometix** [comment]
> Yes I've solved it by using ConfigModule like this:
> 
> ```
>  import { Module } from '@nestjs/common';
>  import { ConfigService, ConfigModule } from '@nestjs/config';
>  
>  @Module({
>      imports: [
>          WinstonModule.forRootAsync({
>              imports: [ConfigModule],
>             inject: [ConfigService],
>              useFactory: (configService: ConfigService) => (
>                   configService.get('logger.config')
>              ),
>          }),
>     ],
> })
> export class LoggerModule {}
> ```

Hi @rainercedric23 
can you help me to provide some code, how you implemented it?
will be very helpful for me, I am stuck in something same usecase.
