### ISSUE TITLE
Constant for inject token

### ISSUE THREAD

**Issue by baocancode** [gremo/nest-winston#130]
Hi, in the README, there is this example:

```
@Inject('winston') private readonly logger: Logger
```

I do not want to type the token 'winston' all the time to avoid typo, also it can change in the future. Best to have a constant for it. I can see this one from type definition:

```
export declare const WINSTON_MODULE_PROVIDER = "winston"
```

Is it supposed to be the inject token? If so, the README should mention about it.

**Comment by gremo** [comment]
Yes, it's `WINSTON_MODULE_PROVIDER` constant. Do you think that README should be updated?

**Comment by baocancode** [comment]
I think so, similar to WINSTON_MODULE_NEST_PROVIDER has been mentioned.

**Comment by baocancode** [comment]
Thanks for quick response.
