### ISSUE TITLE
Can not record trace message when use as the main Nest logger

### ISSUE THREAD

**Issue by luokuning** [gremo/nest-winston#134]
As the document states, we can replace the system logger with Winston logger like this:

```typescript
import { WINSTON_MODULE_NEST_PROVIDER } from 'nest-winston';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));
}
bootstrap();
```

However, when Nest catches an exception, the `trace` message is missing in log file. I think it's because Winston logger instance doesn't conform Nest `LoggerService`.

As a workaround, we should use logger instance return from `WinstonModule.createLogger`.

**Comment by luokuning** [comment]
#73 There is another issue mentioned that. Closed.

**Comment by gremo** [comment]
Hi, feel free to suggest any improvement in the documentation, if there is something unclear.
