### ISSUE TITLE
[FeatureRequest] Child loggers creation with use of forFeature

### ISSUE THREAD

**Issue by koper89** [gremo/nest-winston#137]
Hello,

I wanted to be able to use "filename/moduleName" in my logging. To do this it would be nice to use child logger functionality of winston. Currently I use it as follows:
``export` class Features {
    constructor(
        @Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger
    ) {
        this.logger = logger.child({ module: 'Features'});
    }
}``

This way all logs in this "provider" will be marked with moduleName without need to pass it in each query. Much nicer way would be to use forFeature method on Dynamic Module which would create a child instance for each module.

**Comment by gremo** [comment]
Are you able to work on a PR implementing this feature?

**Comment by gremo** [comment]
Closing, feel free to explain the feature or maybe make a PR to implement it.
