### ISSUE TITLE
Using the same instance for both bootstrap and whole project logging.

### ISSUE THREAD

**Issue by BeaRRRRR** [gremo/nest-winston#140]
Maybe I didn't understand the docs fully, but it seems to me as thought we use two different logger instances for across the whole project logging, e.g.
```
import { Module } from '@nestjs/common';
import { WinstonModule } from 'nest-winston';
import * as winston from 'winston';

@Module({
  imports: [
    WinstonModule.forRoot({
      // options
    }),
  ],
})
export class AppModule {}
```

and for logging during bootstrap, e.g.

```
import { WinstonModule } from 'nest-winston';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: WinstonModule.createLogger({
      // options (same as WinstonModule.forRoot() options)
    })
  });
}
bootstrap();
```

For across the project logging we use whatever `WinstonModule.forRoot` returns, and for logging during the bootstrap we use whatever `WinstonModule.createLogger` returns. So it's like using two different loggers, or at least two different instances.

If I, let's say, want to move the logic associated with creating a logger to another file, so then I could import it. My logger file would look like this.

```
export const bootstrapLogger = WinstonModule.createLogger(options);
export const projectLogger = WinstonModule.forRoot(options); 
```

Is there any way to "combine" bootstrapLogger and projectLogger into just one instance?

**Comment by gremo** [comment]
You got the point. In fact, the two underlying methods return a new (different) instance of `WinstonLogger`.

How do you retrieve the Nest logger from `app` (that is, normally)? On idea could be replacing the entire provider with a factory that returns the Nest logger (which was replaced by our logger).

**Comment by idrisadetunmbi** [comment]
I find this interesting a bit as well cos I am just trying out nestjs and this logger plugin. I am wondering what the difference is between retrieving a single instance registered by the module as the main nest logger:

```
import { WINSTON_MODULE_NEST_PROVIDER } from 'nest-winston';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));
}
bootstrap();
```

or using a non-DI instance:
```
import { WinstonModule } from 'nest-winston';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: WinstonModule.createLogger({
      // options (same as WinstonModule.forRoot() options)
    })
  });
}
bootstrap();
```

**Comment by gremo** [comment]
Hi @idrisadetunmbi, I improved the README in 6157eebfad1e327866b2817cdb76235783824c5e. It should be clear now how to accomplish what you are asking.

Feel free to comment further!
