### ISSUE TITLE
Still unable to inject config

### ISSUE THREAD

**Issue by markau** [gremo/nest-winston#142]
I am using the new **imports** declaration but still unable to inject Config (or environment) variables, they are undefined. 

Below is my main module:

````
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    WinstonModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        level: 'info',
        format: winston.format.combine(
          winston.format.timestamp(),
          winston.format.splat(),
          winston.format.json()
        ),
        transports: [
          new winston.transports.Console({
            level: configService.get<string>('LOG_LEVEL'),
          }),
        ],
    }),
    inject: [ConfigService],
  }),
  FooModule
  ],
  controllers: [FooController],
  providers: [FooService],
})
export class AppModule {}

````

The `WinstonModule` declaration above is identical to my `SequelizeModule` below (which works):

````
    SequelizeModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
      dialect: 'mssql',
      dialectOptions: {
        options: {
          encrypt: true
        }
      },
      host: configService.get<string>('DATABASE_HOST'),
      port: configService.get<number>('DATABASE_PORT'),
      username: configService.get<string>('DATABASE_USER'),
      password: configService.get<string>('DATABASE_PASSWORD'),
      database: 'CatFacts',
      models: [Fact, Animal, FactAnimal],
    }),
    inject: [ConfigService]
  }),
````

**Comment by gremo** [comment]
Hi, can you please setup a minimal working example repository?

**Comment by gremo** [comment]
Also, have you looked at this warning?

> Caveats: because the way Nest works, you can't inject dependencies exported from the root module itself (using exports). If you use forRootAsync() and need to inject a service, that service must be either imported using the imports options or exported from a global module.

**Comment by markau** [comment]
Hi Marco, thanks for the reply and your efforts with this library.

Yes, I read that many times, and sanity checking my implementation was part of the reason for my posting. 

I am using `WinstonModule.forRootAsync()` because I also need to import the ConfigModule. So, in the WinstonModule.forRootAsync({}) properties, I have `imports: [ConfigModule]`. I believe this injects the config module (i.e. makes it available) for the WinstonModule to consume. Is this right, or am I on the wrong track?

**Comment by gremo** [comment]
Hi @markau, good to know! So, make a minimal repository so I can figure out why it doesn't work.

**Comment by markau** [comment]
I was not able to reproduce this in a new NestJS application. I noticed the new, minimal application was using `nest-winston` 1.3.4, which was released 20 hours ago. The old app was using 1.3.3, upgraded to 1.3.4, problem solved 🎉 

Looking at the commits for 1.3.3 -> 1.3.4 I am not sure how to explain this... but, it works, so feel free to close the issue?

**Comment by gremo** [comment]
I'm happy that is working now.

Honestly, can't explain. The only relevant difference from 1.3.3 abd 1.34 was this PR https://github.com/gremo/nest-winston/pull/145.
