### ISSUE TITLE
Using nestLike formatter throws error when tries to log a circular object structure

### ISSUE THREAD

**Issue by TapaiBalazs** [gremo/nest-winston#144]
I use `nest-winston` for l logging in my NestJS application. I am using a third-party lib to handle some business logic and in some cases, it throws a circular object structure error.

When this happens, I get the following error:

```
2020-04-20 09:31:20 [ExceptionsHandler] [error] Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'someProperty' closes the circle
    TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'someProperty' closes the circle
    at JSON.stringify (<anonymous>)
    at Printf.template (/my_project/node_modules/nest-winston/dist/winston.utilities.js:23:17)
```

After some research, I have found that the `winston` package uses `fast-safe-stringify` in order to avoid these kinds of errors. See [here](https://github.com/winstonjs/logform/pull/35)

The error comes from the `winston.utilities.ts` file when it tries to JSON.stringify the meta property.

*Expected behaviour:*
- the `nestLike` formatter handles circular JSON structures using `fast-safe-stringify`

**Comment by gremo** [comment]
Hi, interesting thing. So where `fast-safe-stringify` should be used?

You mean, instead of `JSON.stringify` method?

**Comment by TapaiBalazs** [comment]
Hi!

Yes, exactly, instead of JSON.stringify() method. So the nestLike formatter would look something like the following:

```
import { green, yellow } from 'colors/safe';
import { format } from 'winston';
import * as jsonStringify from 'fast-safe-stringify';

const nestLikeConsoleFormat = () => format.printf(({ context, level, timestamp, message, ...meta }) => {
  return `${green('[NestWinston]')} ` +
         `${yellow(level.charAt(0).toUpperCase() + level.slice(1))}\t` +
         ('undefined' !== typeof timestamp ? `${new Date(timestamp).toLocaleString()} ` : '') +
         ('undefined' !== typeof context ? `${yellow('[' + context + ']')} ` : '') +
         `${green(message)} - ` +
         `${jsonStringify(meta)}`; // <-- here
});

export const utilities = {
  format: {
    nestLike: nestLikeConsoleFormat,
  },
};
```

**Comment by gremo** [comment]
Thanks. Working on it right now.

**Comment by gremo** [comment]
Thanks for helping, checkout v1.3.4.

**Comment by TapaiBalazs** [comment]
@gremo I have installed 1.3.4 and tried it out. Circular JSON issue is no longer present.

Thank you very much for the extremely quick fix! :)
