### ISSUE TITLE
Override formating per module?

### ISSUE THREAD

**Issue by twigs67** [gremo/nest-winston#154]
Hello,

Is there a way to override format options per module? 

For instance, my ```app.module.ts``` looks like:
```
 imports: [
    WinstonModule.forRoot({
      transports: [...],
      format: combine(
        label({ label: 'CONTROLLER_NAME' }),
        timestamp(),
        myFormat,
      ),
    }),
```

And I'm calling it as such: 
```
@Controller('SomeController')
export class SomeController {
  constructor(
    @Inject('winston')
    private readonly logger: Logger,
  ) {}
```

With the nest logger I would be able to add something like setContext. Is there any way to achieve this?

Thanks

**Comment by gremo** [comment]
Maybe [this integration](https://github.com/gremo/nest-winston/commit/bb8530cc153a290219dad127f4ccbb2e06f3c0dd) is what you are looking for?

However, the `setContext` method is available when you use Winston module as your main logger service, not when using the dependency injection. In other words, the loggers are two distinct, different instances.

**Comment by gremo** [comment]
Closing, feel free to comment further if you need any help.
