### ISSUE TITLE
Nest can't resolve dependencies 'Logger' provider

### ISSUE THREAD

**Issue by liemlylac** [gremo/nest-winston#172]
Many thanks for module, I have added to my personal project, following [readme](https://github.com/gremo/nest-winston#use-as-the-main-nest-logger-also-for-bootstrapping), everything is fine for me until apply NestWinston as default (also for bootstrapping) I cannot start project.

Please help me to point out my mistake, may I misunderstanding for 

> This works because Nest Logger wraps our winston logger (the same instance returned by the createLogger method) and will forward all calls to it.

Details of log is showing like this: 

```console
Nest can't resolve dependencies of the UserService (?, HashService, UserRepository). Please make sure that the argument Logger at index [0] is available in the Us
erModule context.

Potential solutions:
- If Logger is a provider, is it part of the current UserModule?
- If Logger is exported from a separate @Module, is that module imported within UserModule?
```
Here is my `main.ts`
```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: WinstonModule.createLogger({
      format: winston.format.json(),
      defaultMeta: { service: 'bootstrap' },
      transports: [
        new winston.transports.Console({
          format: winston.format.combine(
            winston.format.timestamp(),
            utilities.format.nestLike(),
          ),
        }),
        new winston.transports.File({
          filename: __dirname + '/log/error.log',
          level: 'error',
        }), // - Write all logs with level `error` and below to `error.log`
        new winston.transports.File({
          filename: __dirname + '/log/combined.log',
        }),
        // - Write all logs with level `info` and below to `combined.log`
      ],
    }),
    cors: true,
  });

  const configService = app.get(ConfigService);

  await app.listen(configService.get<number>('port'));
}
bootstrap();
```

My `app.module.ts` file
```ts

@Module({
  providers: [Logger],
})
export class AppModule {}
```
My `user.service.ts` file:

```ts
@Injectable()
export class UserService {
  constructor(
    @Inject(Logger)
    private readonly logger: LoggerService,
    private readonly hashService: HashService,
    private readonly userRepo: UserRepository,
  ) {}
}
```

**Comment by gremo** [comment]
Hi @liemlylac are you sure you are using the Logger form '@nestjs/common'?

Also, take a look to https://github.com/nestjs/nest/issues/4868 issue I opened for asking how to inject the Nest logger.

**Comment by liemlylac** [comment]
Yeah, by restore all code, I still couldn't inject Logger (from `@nestjs/comm`), I am trying to create my own logger service (for core module) which extends Logger (from `@nestjs/comm`) and using `NestFactory.create(AppModule, logger: WinstonModule.createLogger({...})` in my `main.ts` file, now I can inject my winston logger (also for bootstrapping) to my service. Thanks you so much

**Comment by gremo** [comment]
You're welcome! Glad to know 👍
