### ISSUE TITLE
Adding transports based on environment

### ISSUE THREAD

**Issue by btorresbrandcoders** [gremo/nest-winston#18]
Since the config options are placed inside the module import in the AppModule, I can't get transports to be added based on which environment the app is running in. Normally using winston, the logger is instantiated in a variable which can be accessed later to add a transport like this:
```javascript
if (process.env.NODE_ENV !== 'production') {
  logger.add(new transports.Console({
    format: format.combine(
      format.colorize(),
      format.simple()
    )
  }));
}
```
Where should the code above (or similar) be used to add the transport?

**Comment by gremo** [comment]
Hi @btorresbrandcoders, maybe you can use `forRootAsync` method? Try if this works (`push` to `transports `array):

```typescript
import { Module } from '@nestjs/common';
import { WinstonModule } from 'nest-winston';
import * as process from 'process';
import * as winston from 'winston';

@Module({
  imports: [
    WinstonModule.forRootAsync({
      useFactory: () => {
          const transports = [];

          if (process.env.NODE_ENV !== 'production') {
            // push a new transport to the transports array
          }

          return {
              transports: transports,
          };
      },
      inject: [],
    }),
  ],
})
export class AppModule {}
```

**Comment by gremo** [comment]
Closing... let me know if you solved the problem.
