### ISSUE TITLE
can i get a full example of how to implement and log?

### ISSUE THREAD

**Issue by rubiin** [gremo/nest-winston#182]
I am using forRoot method and injecting  using `@Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger`. however when i do this.logger.log('some message') i get an error

```
TypeError: Cannot create property 'Symbol(level)'

```

using transaport.console and transport.file

**Comment by gremo** [comment]
Hi @rubiin , please post the full configuration that you are using. Also, try first to update the `winston` package. It has been updated recently, maybe it's their fault.

**Comment by rubiin** [comment]
iam importing like this in app.module

```
	WinstonModule.forRoot({
			transports: [new winston.transports.Console({
				level: 'info',
				handleExceptions: false,
				format: winston.format.combine(
					winston.format.timestamp(),
					utilities.format.nestLike(),
				),
```

and in a controller of my usermodule , i am injecting as 
```
@Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger
```


and using the logger as  ``` this.logger.log('')```

**Comment by rubiin** [comment]
@gremo

**Comment by gremo** [comment]
Sorry forgot to reply. Honestly, I don't know what's is going on here. Are you able to create a repository (minimal example) for this issue?

**Comment by marcelom56** [comment]
@gremo , I had the same problem than you. I solved passing the context (in the first argument) to `log` function.


```Typescript
this.logger.log('Hello!!');  // exception  Cannot create property 'Symbol(level)' on string 'Hello!!'
```

```Typescript
this.logger.log('info', 'Hello!!');  // it works!
```

**Comment by gremo** [comment]
@marcelom56 @rubiin if you are using `WINSTON_MODULE_PROVIDER` injection token, like this example:

```typescript
import { Controller, Inject } from '@nestjs/common';
import { WINSTON_MODULE_PROVIDER } from 'nest-winston';
import { Logger } from 'winston';

@Controller('cats')
export class CatsController {
  constructor(@Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger) { }
}
```

... it means you are using the `winston` package "directly". Looking at the package [README](https://github.com/winstonjs/winston), I can't see any evidence of using `logger.log` without specify any level, that might cause the error reported.

```javascript
//
// Logging
//
logger.log({
  level: 'info',
  message: 'Hello distributed log files!'
});

logger.log('info', 'test message %s', 'my string');
```

TLTR: always specify a level when using `logger.log` as provved by @marcelom56 .

I'm going to close this issue as it seems not related to the `nest-winston` package. Feel free to comment further if I've misunderstood the problem.

**Comment by rubiin** [comment]
sure that helps

**Comment by opensas** [comment]
I stumbled upon the same problem.

I found [this issue](https://github.com/winstonjs/winston/issues/1166) at winston repo:

> Leaving this here for others who come to this thread. The winstonlogger object does have a .log() method. However, unlike console.log(), it requires two arguments, not just one. If you forget the first argument, the log message category, you will get the Symbol(level) error.

[source](https://github.com/winstonjs/winston/issues/1166#issuecomment-432660829)

This is how I'm using it:

```typescript
import { Controller, Get, Inject, Logger } from '@nestjs/common';
import { AppService } from './app.service';
import { WINSTON_MODULE_PROVIDER } from 'nest-winston';

@Controller()
export class AppController {
  constructor(
    private readonly appService: AppService,
    @Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger
  ) {}

  @Get()
  getHello(): string {
    this.logger.log('hello!!!')   // TypeError: Cannot create property 'Symbol(level)' on string 'hello!!!'
    this.logger.log('info', 'hello!!!')   // ok
    return this.appService.getHello();
  }
}
```

It seems inconsistent with nestjs Logger (vscode tooltip displays: `(method) Logger.log(message: any, context?: string): void`)

Perhaps we should override winston log method to make it work like nestjs. Here is a suggested [workaround](https://github.com/winstonjs/winston/issues/1166#issuecomment-457838509)

**Comment by opensas** [comment]
Moreover, from winston doc, every example given with logger.log receives the log level as first parameter, and in the [ using loggin levels](https://github.com/winstonjs/winston#using-logging-levels) section says: 
> Setting the level for your logging message can be accomplished in one of two ways. You can pass a string representing the logging level to the log() method or use the level specified methods defined on every winston Logger.

**Comment by empz** [comment]
I'm sorry but this shouldn't be closed.

If by injecting the Winston logger by doing the following, it seems we end up with the actually Winston logger instance (and not a logger through nest logger interface).
```
@Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger
```

So I think the injection should be:
```
@Inject(WINSTON_MODULE_PROVIDER) private readonly logger: WinstonLogger
```

And the typings should be fixed.
```
import { Logger } from 'winston';
import { LoggerService } from '@nestjs/common';
export declare class WinstonLogger implements LoggerService {
    private readonly logger;
    private context?;
    constructor(logger: Logger);
    setContext(context: string): void;
    log(level: string, message: any, context?: string): any; // Adding level as a first argument
    error(message: any, trace?: string, context?: string): any;
    warn(message: any, context?: string): any;
    debug?(message: any, context?: string): any;
    verbose?(message: any, context?: string): any;
}
```

**Comment by rubiin** [comment]
yes that should be done

**Comment by gremo** [comment]
@empz I've updated the README, please can you check it out and see if something is wrong or unclean (especially about the injection token)?

Typings are correct. If you look at the [`LoggerService`](https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L11) from Nest, you can see that the log function doesn't define any level. You are probably talking about the `log` from winston package.

In addition, I'm working on providing samples which should help people with the token/typings. 👍
