### ISSUE TITLE
how to log http requests (something like morgan)

### ISSUE THREAD

**Issue by opensas** [gremo/nest-winston#233]
Is there some example to tell winston to automatically log http requests?

Something similar to just doing:

```javascript
app.use(morgan('combined', { stream: winston.stream }));
```

Or to what you can achieve with [express-winston](https://github.com/bithavoc/express-winston)

**Comment by gremo** [comment]
Hi @opensas , I think that the right way to do this is to implement a [custom interceptor](https://docs.nestjs.com/interceptors) (if using this library with dependency injection). If you are using nest-wiston as the main Nest logger then it should log requests automatically.

I'm closing this, feel free to reply if you have any quesiton.

**Comment by rubiin** [comment]
> Hi @opensas , I think that the right way to do this is to implement a [custom interceptor](https://docs.nestjs.com/interceptors) (if using this library with dependency injection). If you are using nest-wiston as the main Nest logger then it should log requests automatically.
> 
> I'm closing this, feel free to reply if you have any question.

can you give an example snippet

**Comment by opensas** [comment]
I tried setting nest-winston as the main nest logger as described [here](https://github.com/gremo/nest-winston#use-as-the-main-nest-logger-also-for-bootstrapping) but it won't log requests.

I also think it would be great to have working examples or snippets for these basic usage scenarios.

**Comment by rubiin** [comment]
yeah, I think there should be examples directory with some code for working examples

**Comment by YuriiZadorozhnyi** [comment]
Can someone provide an example of how to add "nest-winston" to the project to log HTTP requests?

**Comment by roddc** [comment]
I think we could write an Interceptor or use a lib to log the requests

**Comment by kd496** [comment]
See #454 for a solution.
