### ISSUE TITLE
How to pass in dynamic label?

### ISSUE THREAD

**Issue by ShareinSK** [gremo/nest-winston#238]
I have used Nest-Winston for main logging including bootstrap.

This is my configuration

```
{
    transports: [new transports.Console({
        level: 'debug'
    })],
    format: f.combine(
        format.colorize({ all: true }),
        format.splat(),
        format.simple(),
        format.timestamp(),
        nestWinstonModuleUtilities.format.nestLike()
    ),
    exitOnError: false
}
```

And this is what it logs now `[NestWinston] debug     9/30/2020, 12:56:51 PM debug - {"abc": "xyz"}`

How do I print the class name where the error occurred in the place of `NestWinston` ?

I tried with label but it wasn't dynamic.

**Comment by gremo** [comment]
You're right, the first argument of `nestLike` is just the application name. In order to use "dynamic" label you could use the `context` argument or `setContext` method?

**Comment by ShareinSK** [comment]
But when using NestWinston for bootstrapping it does not provide the `context` or `setContext` method.

```constructor(
    @Inject(Logger) private readonly logger: LoggerService) {
    }
```

Can you provide an example of how to do that?

**Comment by TrejGun** [comment]
@ShareinSK enjoy

```
import {Injectable} from "@nestjs/common";
import {WinstonModuleOptions, WinstonModuleOptionsFactory} from "nest-winston/dist/winston.interfaces";
import {format, transports} from "winston";
import cls from "cli-color";

@Injectable()
export class WinstonConfigService implements WinstonModuleOptionsFactory {
  createWinstonModuleOptions(): WinstonModuleOptions {
    return {
      format: format.combine(format.errors({stack: true}), format.timestamp()),
      transports: [
        new transports.Console({
          format: format.printf(args => {
            const {level, context, timestamp, message, stack, trace} = args;
            let color = cls.green;
            let text = "";
            if (level === "error") {
              color = cls.red;
              const lines = (stack || trace).split("\n");
              lines[0] = color(lines[0]);
              text = lines.join("\n");
            } else if (level === "info") {
              color = cls.green;
              text = color(message);
            } else if (level === "warn") {
              color = cls.yellow;
              text = color(message);
            } else if (level === "debug") {
              color = cls.magentaBright;
              text = color(message);
            } else if (level === "verbose") {
              color = cls.cyanBright;
              text = color(message);
            }

            return `${color(`[Nest] ${process.pid}   -`)} ${new Date(timestamp).toLocaleString()}   ${
              context ? cls.yellow("[" + context + "]") : ""
            } ${text}`;
          }),
        }),
      ],
    };
  }
}
```

**Comment by ShareinSK** [comment]
@TrejGun Thanks for the example, it worked.

But in the given example, the `context` needs to be added as a second arg to every logger command.

Is there an option to initialize the logger inside the class constructor with the `context`, so that everytime the context need not be specified in a class.

**Comment by TrejGun** [comment]
ask @gremo

**Comment by ShareinSK** [comment]
@gremo Is there an option to initialize the logger inside the class constructor with the context, so that everytime the context need not be specified in a class.

If we could do something like

    _logger: any;
    constructor(@Inject(WINSTON_MODULE_NEST_PROVIDER) private logger: LoggerService) {
        this._logger = logger.setContext('ClassName');
    }

**Comment by ShareinSK** [comment]
Closing this but opening a new ticket for single instantiation of logger.
