### ISSUE TITLE
how to use inside a filter

### ISSUE THREAD

**Issue by rubiin** [gremo/nest-winston#243]
I want to use this inside a filter where i am catching all 500 exceptions. can anyone provide me with some snippet to get going

**Comment by gremo** [comment]
Hi, what do you mean "Use this inside a filter"?

**Comment by rubiin** [comment]
i want to use the logger as to log response inside a filter

**Comment by gremo** [comment]
There is no built-in method to log request and response, it's up to the developer. However, you can use any third party library like `@algoan/nestjs-logging-interceptor` (or try to just google for a more popular one). 

Also take a look at https://github.com/gremo/nest-winston/issues/268 where I provide an example to log request and response using that libray.

**Comment by rubiin** [comment]
@gremo can we make file transports optional. I only want them when NODE_ENV = production . for other environments, I only want console transaport

**Comment by gremo** [comment]
@rubiin have you see my example? Is this what you want? For making transport optional it fairly easy with a conditional.

**Comment by rubiin** [comment]
> @rubiin have you see my example? Is this what you want? For making transport optional it fairly easy with a conditional.

yeah , I used the other i@algoan/nestjs-logging-interceptor works out of the box for my need

**Comment by gremo** [comment]
Good to know!

**Comment by rubiin** [comment]
can you provide me a snippet for making transport optional

**Comment by gremo** [comment]
It could work this way (not tested) assuming `app.modules.ts`:

```ts
// Common Winston transorts
let transports: winston.transport[] = [
  new winston.transports.Console({
    format: winston.format.combine(
      winston.format.timestamp(),
      nestWinstonModuleUtilities.format.nestLike(),
    ),
  }),
];

// Production Winston trasport (common + custom)
if ('production' === process.env.NODE_ENV) {
  transports = [
    ...transports, new winston.transports.File({
      filename: 'logs/error.log',
      level: 'error',
    }),
  ]
}

@Module({
  imports: [
    WinstonModule.forRoot({
      transports: transports
    }),
  ],
})
export class AppModule {}
```

**Comment by rubiin** [comment]
cool
