### ISSUE TITLE
Use as the main Nest logger (also for bootstrapping) is not working

### ISSUE THREAD

**Issue by JustDoItSascha** [gremo/nest-winston#244]
I tried to implement the module as described in the chapter "Use as the main Nest logger (also for bootstrapping)", but I always get the errors with `Nest can't resolve dependencies`. Is this chapter still working with Nest 7.4.2?

**Comment by gremo** [comment]
Thanks for opening the issue. I'm quite busy right now but I'll check this weekend.

**Comment by ShareinSK** [comment]
@JustDoItSascha  I was able to setup as the Main Nest logger. Could share some code on how you configured?

**Comment by JustDoItSascha** [comment]
@ShareinSK Yeah setting as the main logger works, but could you import it in the AppModule / other Services?

Like it stands in the docs:

```
import { Logger, Module } from '@nestjs/common';

@Module({
    providers: [Logger],
})
export class AppModule {}
```

and 

```
import { Controller, Inject, Logger, LoggerService } from '@nestjs/common';

@Controller('cats')
export class CatsController {
  constructor(@Inject(Logger) private readonly logger: LoggerService) { }
}
```

Because this is the part which is not working, Nest can't find `LoggerService`.

**Comment by gremo** [comment]
@ShareinSK thanks for helping in this issue. @JustDoItSascha I'll check in a couple of hours, maybe the documentation is not clear enough or maybe a bit outdated.

**Comment by gremo** [comment]
Hi @JustDoItSascha , I can confirm that the module still works with the latest version. Documentation seems fine, here is what i did, I used the `nest` utility (`npm i -g @nestjs/cli`):

```bash
nest new nestjs-playground
npm install --save nest-winston winston
```

Then, I followed the instructions in the docs ("Use as the main Nest logger (also for bootstrapping)"). 

Here is some files, hope this helps to you:

```typescript
// app.module.ts
import { Logger, Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService, Logger], // THIS IS IMPORTANT!
})
export class AppModule {}
```

```typescript
// main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { WinstonModule, utilities as nestWinstonModuleUtilities } from 'nest-winston';
import * as winston from 'winston';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: WinstonModule.createLogger({
      transports: [new winston.transports.Console({
        format: winston.format.combine(
          winston.format.timestamp(),
          nestWinstonModuleUtilities.format.nestLike(),
        ),
      })],
    })
  });
  await app.listen(3000);
}
bootstrap();
```

```typescript
// app.controller.ts
import { Controller, Get, Inject, Logger, LoggerService } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService,
    @Inject(Logger) private readonly logger: LoggerService) {}

  @Get()
  getHello(): string {
    this.logger.log('Inside AppController');

    return this.appService.getHello();
  }
}
```

**Comment by taivy** [comment]
I had same issue. The problem was that I was using logger in imported modules, not in app module directly. 

So my app.module.ts was like this:
```
@Module({
  imports: [
    MyModule
  ],
  providers: [Logger],
  exports: [Logger],
})
export class AppModule {}
```
and logger was used in MyModule.service.ts like this

```
import { Injectable, Inject, Logger, LoggerService } from '@nestjs/common';

@Injectable()
export class MyModuleService {
  constructor(@Inject(Logger) private readonly logger: LoggerService) {}
}
```

I needed to add Logger to **providers** of MyModule like this:

```
// mymodule.module.ts
import { Module, HttpModule, Logger } from '@nestjs/common';
import { MyModuleService } from './MyModule.service';

@Module({
  imports: [HttpModule],
  providers: [MyModuleService , Logger],
})
export class MyModule {}
```
Also it's not necessary to add Logger to providers in main app module in that case.

**Comment by parikmaan** [comment]
Thanks @taivy and adding comment from @jmcdo29

[Link to comment](https://github.com/nestjs/nest/issues/4868)

> _[The docs mention it with a custom extension](https://docs.nestjs.com/techniques/logger#dependency-injection), but this applies as well to the base class. Everything in nest that is to be injected needs to be A) in a module's providers array and B) in the context of the current module. With things like the Reflector and ModuleRef, those are globally scoped, so it's not necessary to add them,_ but the Logger class is not in a global module, **so it needs to be added to the providers array of the current module**
