### ISSUE TITLE
Initializing logger with setContext inside constructor

### ISSUE THREAD

**Issue by ShareinSK** [gremo/nest-winston#247]
@gremo Is there an option to initialize the logger inside the class constructor with the context, so that everytime the context need not be specified in a class.

If we could do something like

    _logger: any;
    constructor(@Inject(WINSTON_MODULE_NEST_PROVIDER) private logger: LoggerService) {
        this._logger = logger.setContext('ClassName');
    }

    async test() {
        this._logger.log('Hello World');
    }

**Comment by gremo** [comment]
The class [`WinstonLogger`](https://github.com/gremo/nest-winston/blob/master/src/winston.classes.ts#L5) from `nest-winston` implements [`LoggerService`](https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L11) from `nestjs/common`, which is an interface and **doesn't define any `setContext` method**.

However, as you may notice, both the `WinstonLogger` and the original [`Logger`](https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L20) from `nestjs/common` are implementations and have a `setContext` method. So, to avoid a TypeScript error (as I guess) you can force the type:

```typescript
import { Controller, Get, Inject, Logger, LoggerService } from '@nestjs/common';
import { WinstonLogger } from 'nest-winston';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService,
    @Inject(Logger) private readonly logger: LoggerService) {
      (logger as WinstonLogger).setContext('AppController');
    }

  @Get()
  getHello(): string {
    this.logger.log('Inside AppController');

    return this.appService.getHello();
  }
}
```

Note that if you change the implementation, this will not work anymore.
