### ISSUE TITLE
Best approach for unit testing modules

### ISSUE THREAD

**Issue by jembach** [gremo/nest-winston#253]
Hi, 

I have recently started using this package. As I run my unit tests all tests failed that are injecting the logger.

```
Nest can't resolve dependencies of the [SERVICE] (?, ANOTHER_SERVICE). Please make sure that the argument NestWinston at index [0] is available in the RootTestModule context.
```

I'm using the [Quick start example](https://github.com/gremo/nest-winston#quick-start) for implementing `nest-winston`.
For testing I'm using the provided way by the `nestjs` [docs](https://docs.nestjs.com/fundamentals/testing#testing-utilities).

Could anyone provide an example how to mock this package for testing?

**Comment by gremo** [comment]
Can you plase create a minimal repository so I can give it a look?

**Comment by jembach** [comment]
Hi @gremo,

after studying the docs of nestjs and some examples I found a solution that fits my testing cases.

```javascript

import { Test, TestingModule } from '@nestjs/testing';
import { WINSTON_MODULE_PROVIDER } from 'nest-winston';

const LoggerMock = {
  log: jest.fn(),
  error: jest.fn(),
  warn: jest.fn(),
  debug: jest.fn(),
  verbose: jest.fn(),
};

module = await Test.createTestingModule({
      controllers: [SOME_CONTROLLER],
      providers: [
        { provide: WINSTON_MODULE_PROVIDER, useValue: LoggerMock },
      ],
    }).compile();
```

So I'm just manual injecting the winston logger with a custom mock.

**Comment by Carl-Meyer** [comment]
this is what I did and it seemed to have worked for me, not sure if this has an impact on testing performance. Using a mock is probably better. 

```
module = await Test.createTestingModule({
      imports: [WinstonModule.forRoot({ transports: [new winston.transports.Console()] })],
      controllers: [SOME_CONTROLLER],
      providers: [
        { provide: WINSTON_MODULE_PROVIDER, useValue: LoggerMock },
      ],
    }).compile();
```

**Comment by NomadXD** [comment]
@Carl-Meyer it worked for me as well. Thank you.
