### ISSUE TITLE
Unable to inject Logger in Repository and logrotate function

### ISSUE THREAD

**Issue by Meywether** [gremo/nest-winston#258]
Hello,
thanks for your great work here.
I do have a question:

I was unable after following your tutorial using nest-winston as nestjs logger to use it inside a repository class:

Here some code:

```
import { ConflictException, Inject, InternalServerErrorException, LoggerService } from "@nestjs/common";
import { WINSTON_MODULE_NEST_PROVIDER } from "nest-winston";
import { EntityRepository, Repository } from "typeorm";
import { AuthCredentialsDto } from "./dto/auth-credentials.dto";
import { User } from "./user.entity";

@EntityRepository(User)
export class UserRepository extends Repository<User> {
    constructor(@Inject(WINSTON_MODULE_NEST_PROVIDER) private readonly logger: LoggerService) {        
        super()
    }

    async signUp(authCredentialsDto: AuthCredentialsDto): Promise<void> {

        const { username, password, primaryEmailAddress } = authCredentialsDto

        const user = new User();
        user.username = username;
        user.password = password;
        user.primaryEmailAddress = primaryEmailAddress;
        
        try {
            await user.save()
        } catch(error) {
            // Catches duplicated Entry Error
            if (error.code === 'ER_DUP_ENTRY') {
                this.logger.error(`User with name ${user.username} tried to be registered a second time.`)
                throw new ConflictException('Username already exists')
            } else {
                throw new InternalServerErrorException();
            }
        }
    }
}
```

When the user is already in the database the line this.logger ... is called, but ending up in this error message:
```TypeError: this.logger.error is not a function``` . This message is also logged to the error.log. But the expected value should be `User with name ${user.username} tried to be registered a second time.`

I straight followed your documentation by creating the logger in this way:

```
app.module.ts

@Module({
  imports: [
  TypeOrmModule.forRoot(configService.getTypeOrmConfig()),
  WinstonModule.forRoot({
    transports: [
      new winston.transports.Console({
        format: winston.format.combine(
          winston.format.timestamp(),
          nestWinstonModuleUtilities.format.nestLike(),
        )
      },
    ),
    new winston.transports.File({
      format: winston.format.json(),
      filename: errorLogPath, level: 'error',
      zippedArchive: true,
      tailable: true,      
    }),
    new winston.transports.File({
      format: winston.format.json(),
      filename: infoLogPath, level: 'info',
      zippedArchive: true,
      tailable: true,      
    })
    ],

  }),
  AuthModule
],
  controllers: [],
  providers: []
})
export class AppModule {}
```
Here my second question arises: How can I use logrotate? It wants a function, can you provide me an example? I want to daily rotate my logs.

Thanks in advance!!

Best regards
Meywether

**Comment by gremo** [comment]
Hi, if you are using `forRoot` then you need the  `WINSTON_MODULE_PROVIDER` token along with `Logger` type hint from 'winston'. Just look for the Quick Start section 👍🏻

For the second question have a look here: https://github.com/winstonjs/winston-daily-rotate-file

**Comment by Meywether** [comment]
Hello Gremo,
thanks for your response, I decided to change my imports of Winston to be the default logger of nest.
I mean, if you are not a newbie to NestJS like me, than its obvious what the mistake is about, maybe can you extend your documentation with an example like you did in your comment?

Regarding Daily Log Rotate, I was a litte bit confused, because the property was available but no documentation at your side. Thanks for the link!

Thanks a lot!!! 
Meywether

**Comment by Meywether** [comment]
Hello @gremo,
sorry to disturb you again, but I have the same problem again in my repository classes ( only there )
This time I followed: [Quickstart](https://github.com/gremo/nest-winston#use-as-the-main-nest-logger-also-for-bootstrapping).

Again, logger.error, function not defined. 

My module within the repository directory provides the Logger class!

Can it be, that because of the super() call , the injection does not work ?

![image](https://user-images.githubusercontent.com/39849054/99158147-068eb180-26d0-11eb-9768-fe47771fca59.png)


Best regards
Meywether

**Comment by gremo** [comment]
So sorry for the late response, I was a bit busy at work an all the stuff.

Have you solved your issue? AFAIK there is not problem with super(). Just try to `console.log(this.logger)` inside the repository and see if it's `undefined`.

**Comment by Meywether** [comment]
Hi, 
will check it asap!
Best regards
Meywether

**Comment by Meywether** [comment]
Hi, 
took a little but longer due to my work.
No its defined, getting a bunch of logs, the error message is still:
``
[NestWinston] Error     2.3.2021, 14:11:29 [RpcExceptionsHandler] this.logger.log is not a function - {"stack":["TypeError: this.logger.log is not a function\n
``

Best regards Meywether

**Comment by gremo** [comment]
@Meywether if you still have errors, let us know. I'll close this in the meanwhile 😄
