### ISSUE TITLE
Question: How can I insert the context info (module name) into logging

### ISSUE THREAD

**Issue by ppcamp** [gremo/nest-winston#262]
I wanna know if there's any way to insert  (by default) the module name into logging information. I researched and found that the INQUIRER decorator seems to do what I want, however, how can I put this by default? PS.: I'm using the following configurations.

```javascript

WinstonModule.forRoot({
      transports: [
        new winston.transports.File({
          format: winston.format.combine(
            winston.format.simple(),
            winston.format.timestamp({ format: 'YYYY-MM-DD HH:mm:ss' }),
            winston.format.printf(
              info => `[${info.timestamp}] ${info.level} ${info.message}`,
            ),
          ),
          maxsize: 10e6,
          maxFiles: 5,
          filename: `${__dirname}/../logs/log.log`,
        }),
        new winston.transports.Console({
          format: winston.format.combine(
            winston.format.simple(),
            winston.format.timestamp({ format: 'YYYY-MM-DD HH:mm:ss' }),
            winston.format.colorize(),
            winston.format.printf(
              info => `[${info.timestamp}] ${info.level} ${info.message}`,
            ),
          ),
          level: 'debug',
        }),
      ],
    }),
  ],

```

**Comment by gremo** [comment]
Can you provide a link about the INQUIRER decorator? Can't find anything...

**Comment by ppcamp** [comment]
https://github.com/nestjs/docs.nestjs.com/issues/937
https://github.com/nestjs/nest/issues/3819

I couldn't find the another link that I've used to make this question

**Comment by gremo** [comment]
Interesting, so the INQUIRER provides what? `string` or `object` representing the module name or?

**Comment by UXabre** [comment]
> Interesting, so the INQUIRER provides what? `string` or `object` representing the module name or?

The INQUIRER injects an Object with the same prototype as the calling class:

constructor(@Inject(INQUIRER) contextClass: object) {
     this.context = contextClass?.constructor?.name;
}

So the above could be an implemenation but would perhaps be awesome if we'd have a global config (like in the WinstonModule.createLogger option struct) to enable this
