### ISSUE TITLE
How would I use this module with Google's logging-winston middleware?

### ISSUE THREAD

**Issue by elepedus** [gremo/nest-winston#274]
Thanks for the really cool module. I added it into our Nest project using the bootstrap method and everything worked out of the box! 👍 

However, we use Google App Engine in production, and we would like our log output to be grouped by request. Normally, we use @google-cloud/logging-winston to create an express middleware which automagically picks up GAE correlationIds etc. This is explained [in their documentation](https://googleapis.dev/nodejs/logging-winston/latest/). Basically, you call the provided `makeMiddleware` function, passing it your initialised logger. The logger is then attached to your request object.

Unfortunately, `WinstonModule.createLogger` returns a LoggerService, which doesn't expose an interface compatible with the standard Winston logger.

How can I use your module and take advantage of the request-bundling offered by the logging-winston middleware?

**Comment by gremo** [comment]
Hi, glad to ear that all works fine for you 👍 

To the question, where you need to call `makeMiddleware` function, passing the logger instance? If you are using the dependency injection technique (that is using `forRoot` or `forRootAsync`) you should be able to retrieve the winston `Logger` instance (to pass to `makeMiddleware`) using the `WINSTON_MODULE_PROVIDER` injection token.

**Comment by gremo** [comment]
I was able to make it work getting the winston instance from `src/main.ts`:

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import {
  WINSTON_MODULE_NEST_PROVIDER,
  WINSTON_MODULE_PROVIDER,
} from 'nest-winston';
import * as lw from '@google-cloud/logging-winston';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));

  const logger = app.get(WINSTON_MODULE_PROVIDER);
  const logginMiddleware = await lw.express.makeMiddleware(logger);
  app.use(logginMiddleware);

  await app.listen(3000);
}
bootstrap();
```

Of course, I get an error about authorizations, which is good:

![Logging](https://user-images.githubusercontent.com/1532616/103349265-af387b00-4a9c-11eb-862e-bc95e28d3c07.PNG)

Don't forget to use `forRoot` or `forRootAsync` in you app module. Feel free to comment or re-open this issue if you have any problem.
