### ISSUE TITLE
There is no info function in WinstonLogger class

### ISSUE THREAD

**Issue by minhntm** [gremo/nest-winston#276]
I'm surprised that `nest-winton` doesn't provide `info` function, which is used in `winston` [document](https://github.com/winstonjs/winston#using-logging-levels) frequently. Furthermore, `log` function sticks with `info` level. It's very confused and wastes a lot of time when moving from `winston` to `nest-winston`. Why don't we implement `info` and `log` function like the original library? Can I work on PR to implement it?

**Comment by gremo** [comment]
I'ts not something we can implement with a PR, it's a design decision by Nest. When using this module as main Nest logger, you use  an implementation of `LoggerService` interface from Nest package, that interface doesn't provide any `info()` method.

However, when using the dependency injection (in controller, services, etc.) you are directly accessing a `Logger` instance from Winston and the `info()` method exists.
