### ISSUE TITLE
Question: relation between nestjs LoggerService levels and winston levels

### ISSUE THREAD

**Issue by danielevigi** [gremo/nest-winston#284]
What is the relationship between nestjs LoggerService levels and winston levels?

For example if I use `this.logger.info` what level of winston am I using?

**Comment by gremo** [comment]
Hi, thanks for asking. Take a look here: https://github.com/gremo/nest-winston/blob/master/src/winston.classes.ts

Basically:

- **Nest log -> Winston info**
- Nest error -> Winston error
- Nest warn -> Winston warn
- Nest debug - Winston debug
- Nest verbose -> Winston verbose

Do you think this is a relevant information and README should be update?

**Comment by danielevigi** [comment]
thanks

**Comment by danielevigi** [comment]
Sorry, I didn't read the question. Yes, in my opinion it would make sense to have this information in the README
