### ISSUE TITLE
logs are not logged

### ISSUE THREAD

**Issue by rubiin** [gremo/nest-winston#300]
After setting as default logger  with ` app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));`, logs are not logged
I am doing logging as:
`constructor(@Inject(WINSTON_MODULE_NEST_PROVIDER) private readonly logger: LoggerService) { }`

and 

`this.logger.log('some log')`

**Comment by gremo** [comment]
Hi, can you paste at least the contento of the boostrap file and the service where you are trying to inject the logger?

**Comment by gremo** [comment]
Can you please take a look at the updated and improved README to see if the issue persist?

**Comment by gremo** [comment]
Please take a look at the updated README and the upcoming samples. Feel free to comment further if you need help!
