### ISSUE TITLE
Some logs are not automatically injected with dd-trace-js (only through HTTP)

### ISSUE THREAD

**Issue by sevetseh28** [gremo/nest-winston#340]
Hi. I have a HTTP transport to send logs to Datadog, but some of them dont include the automatic tags added by the dd-trace-js package. This only happens with the Http transport.. Im using the WinstonModule.createLogger approach to have all logs sent to Datadog.
All of them are appearing in the console though, with all the trace info.

Has this happened to anyone?

Thanks!

**Comment by gitSambhal** [comment]
Any update on this? None of my logs has trace id.
