### ISSUE TITLE
Nest can't resolve dependencies of the service

### ISSUE THREAD

**Issue by JSEvgeny** [gremo/nest-winston#364]
Hey.

I'm using the first approach from readme with `WinstonModule.forRoot` for `app.module`. I then inject it in my email service thru dependency injection in constructor and everything works as charm so no issue with that.

But my `email.service.spec` is now failing with error `Nest can't resolve dependencies of the EmailService`

`
Potential solutions:
    - If winston is a provider, is it part of the current RootTestModule?
    - If winston is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing winston */ ]
      })
`

But nothing from those hits helped me. Any ideas of what could go wrong there?

**Comment by JSEvgeny** [comment]
In addition to the issue. I was able to successfully mock the logger for module I was using it with, but then another module that is dependent on the first one, has broken tests again even when I use the same mocking approach

**Comment by gremo** [comment]
Hi @JSEvgeny is this still relevant?

**Comment by alesdokshanin** [comment]
@gremo this is relevant for me at this moment. Could you please clarify what is the proper way to test code that injects the following way: `@Inject( WINSTON_MODULE_NEST_PROVIDER) private readonly logger: LoggerService) {}`

**Comment by tzezar** [comment]
anyone?
