### ISSUE TITLE
nestjs 8 compatibility

### ISSUE THREAD

**Issue by TrejGun** [gremo/nest-winston#368]
Heya! 
Now when nestjs 8 is out we would like to know about module compatibility.
Please write a short guide on how to migrate if necessary or just close this issue if there are no changes

**Comment by vschoener** [comment]
I just tried to reinstall with nestjs 8 and I got this:

```
Could not resolve dependency:
npm ERR! peer @nestjs/common@"^5.0.0 || ^6.6.0 || ^7.0.0" from nest-winston@1.5.0
```
So maybe 8 already works out of the box but the requirement needs to be changed before?

**Comment by gremo** [comment]
Thank you for opening the issue. I'll sumply do qhat @vschoener suggested in the next few days, and change the peer dependencies if needed.

**Comment by danshapir** [comment]
v8 also added new functions to the logger that allow passing more variables and not just the context. Please also expose those variables.

**Comment by orecus** [comment]
@gremo any updates on v8 compatibility? :)

**Comment by gremo** [comment]
@orecus I've done a quick test with the basic example, updated to v8, and it works just fine 🥳.Need to test the other samples too, maybe you could help? I can upload the sample/quick-start-v8 if you wish, but it's basically the same as previous sample.

@danshapir I see. What do you think, should I release v2 or just stick with the previous `LoggerService` implementation? Any ideas?

**Comment by danshapir** [comment]
V8 works, just need to update peer dependencies.

I suggest a v2, yeah. Or v1 with supporting both functions, that's what nest did.

**Comment by bm77525-kr** [comment]
Would love to see the peer deps get updated if everything works fine, just to get unblocked, and then maybe a follow-up v2 if that will take a little extra time.

**Comment by gremo** [comment]
I would update it right now (as @bm77525-kr suggested), but I have some issues with Travis CI. My profile has a negative credit balance (???) so builds have been disabled. That's also why the Renovate bot can't automatically merge PRs.

I guess I have to wait next month to get my credit back. Or, if you can help me to resolve the issue, feel free to give me some help 😄

**Comment by NilsLeger** [comment]
Hi @gremo, any updates? Were your Travis CI builds enabled again 😋? Do you need support?

**Comment by gremo** [comment]
Yes, i definitely need some kind of help fixing Travis.

**Comment by maxerbox** [comment]
> Yes, i definitely need some kind of help fixing Travis.

You've used all your credits, and you can't recover them. See https://docs.travis-ci.com/user/billing-overview/#free-plan.


You can ask free monthly credits by asking the travis team, see https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

**Comment by maxerbox** [comment]
Your builds last ~2min40.
We will say that you do 40 builds a month
Let's say ~107 minutes of build.
If you keep using a Linux env : it's 10 credits / minute : https://docs.travis-ci.com/user/billing-overview/#usage---credits

1200 credits should be enough.

**Comment by smn7231** [comment]
> I guess I have to wait next month to get my credit back

Hi @gremo

We stay waiting for update!
Please just update the package.json dependencies

Thanks

**Comment by predam** [comment]
I'm planning to use this in my project
🥇 waiting for the big release

**Comment by schealex** [comment]
> I'm planning to use this in my project
> 🥇 waiting for the big release

same here

**Comment by TrejGun** [comment]
You actually do not need travis at all. you can run tests inside GH actions

**Comment by maxerbox** [comment]
> You actually do not need travis at all. you can run tests inside GH actions

We should submit a PR with the action workflows then !

**Comment by TrejGun** [comment]
https://github.com/gremo/nest-winston/pull/381

**Comment by delucca** [comment]
> I'm planning to use this in my project
> 1st_place_medal waiting for the big release

same here!!

**Comment by FlxEd** [comment]
> I'm planning to use this in my project
> 🥇 waiting for the big release

Can't wait for it as well.
Thanks for the great work !😋

**Comment by danshapir** [comment]
Just an FYI, it works now with v8, just use - - legacy-peer-deps

**Comment by gremo** [comment]
Thanks all guys! Right now I'm on holidays ⛱️ and can't access my workstation, but I'll be back in a few days and finally make this module v8 compatible!

**Comment by ashish-velotio** [comment]
I am eagerly waiting for this

**Comment by ltudisco** [comment]
Same here!

**Comment by gremo** [comment]
So I've merged the #381 thanks to @ubudragon and removed the Travis integration. Now I'm going to test Renovate auto merging feature and then, if all it's fine, I'll add v8 compatibility.

**Comment by dannyphillips** [comment]
Any updates on this @gremo?

**Comment by vtrphan** [comment]
i'm also waiting for a new release

**Comment by olakara** [comment]
Is this issue resolved? I am trying to use this package and not able to install because of dependency issue..

**Comment by gremo** [comment]
@TrejGun @ubudragon can't test locally anymore :( any clue?

```$ npm run test

> nest-winston@1.5.0 test C:\Progetti\gremo\nest-winston
> jest

 FAIL   nest-winston  src/winston.module.spec.ts
  ● Test suite failed to run

    Cannot find module '@nestjs/common/interfaces/version-options.interface' from 'node_modules/@nestjs/core/helpers/messages.js'

    Require stack:
      node_modules/@nestjs/core/helpers/messages.js
      node_modules/@nestjs/core/injector/instance-loader.js
      node_modules/@nestjs/testing/testing-module.builder.js
      node_modules/@nestjs/testing/test.js
      node_modules/@nestjs/testing/index.js
      src/winston.module.spec.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:313:11)
      at Object.<anonymous> (node_modules/@nestjs/core/helpers/messages.js:5:37)
```

**Comment by TrejGun** [comment]
https://github.com/gremo/nest-winston/pull/388/files

it looks like you forget to update @nestjs/common

**Comment by olakara** [comment]
@gremo @TrejGun we will have to update the RxJS as @nestjs/common 8.0.6 needs RxJS 7.1.0

**Comment by gremo** [comment]
Thank you @TrejGun , I'm re-checking right now! @olakara are you sure?

**Comment by TrejGun** [comment]
yes you have to update rx

**Comment by gremo** [comment]
`1.6.0` is out! Thank you ALL of you guys! 🎉🎉🎉
