### ISSUE TITLE
Nest can't resolve dependencies

### ISSUE THREAD

**Issue by Zyles** [gremo/nest-winston#378]
I am having the problem where nest can't find Logger dependency:

```
Nest can't resolve dependencies of the TasksService (?). Please make sure that the argument Logger at index [0] is available in the TasksModule context.

Potential solutions:
- If Logger is a provider, is it part of the current TasksModule?
- If Logger is exported from a separate @Module, is that module imported within TasksModule?
  @Module({
    imports: [ /* the Module containing Logger */ ]
  })

```

I saw a few other issues with this but I didn't find an answer with the solution.

I setup the logger in main.ts and added Logger to providers array in my app.module.ts

Now in my TaskService can't import the logger. Since the logger should be global I shouldn't need to import it in my module?

```
tasks.module.ts:
import { Module } from '@nestjs/common'
import { TasksService } from './tasks.service'

@Module({
  imports: [],
  controllers: [],
  providers: [TasksService],
  exports: [],
})
export class TasksModule {}
```

```
tasks.service.ts:
import { Inject, Injectable, Logger, LoggerService } from '@nestjs/common'
import { Cron, Interval, Timeout } from '@nestjs/schedule'

@Injectable()
export class TasksService {
  constructor(@Inject(Logger) private readonly logger: LoggerService) {}

  @Cron('0 * * * * *')
  handleCron() {
    this.logger.debug('Running cronjobs')
  }
}
```

```
app.module.ts:
@Module({
  imports: [TasksModule],
  controllers: [AppController],
  providers: [AppService, Logger],
})
export class AppModule {}
```

```
main.ts:
import {
  WinstonModule,
  utilities as nestWinstonModuleUtilities,
} from 'nest-winston'
import * as winston from 'winston'

// Winston logging transports
const transports = {
  console: new winston.transports.Console({
    format: winston.format.combine(
      winston.format.timestamp(),
      winston.format.colorize(),
      nestWinstonModuleUtilities.format.nestLike(),
    ),
  }),

  file_error: new winston.transports.File({
    filename: 'logs/error.log',
    level: 'error',
  }),

  file_warn: new winston.transports.File({
    filename: 'logs/warn.log',
    level: 'warn',
  }),

  file_info: new winston.transports.File({
    filename: 'logs/info.log',
    level: 'info',
  }),

  file_debug: new winston.transports.File({
    filename: 'logs/debug.log',
    level: 'debug',
  }),
}

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    logger: WinstonModule.createLogger({
      transports: [
        transports.console,
        transports.file_error,
        transports.file_info,
        transports.file_debug,
        transports.file_warn,
      ],
    }),
  })
  app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)))

  app.enableShutdownHooks()

  if (process.env.NODE_ENV === 'development') {
    app.enableCors()
  } else {
    app.enableCors({ origin: serverConfig.origin })
  }

  const port = process.env.PORT || serverConfig.port
  await app.listen(port)
}
bootstrap()
```

Did I forget something?

**Comment by goranjviv** [comment]
this might help - https://medium.com/@dvirarad/nestjs-custom-logger-with-rabbitmq-injection-da2f40ccddbd

**Comment by goranjviv** [comment]
this part in particular: 
`Because application instantiation (NestFactory.create()) happens outside the context of any module; it doesn't participate in the normal Dependency Injection phase of initialization. So we must ensure that at least one application module imports the LoggerModule to trigger Nest to instantiate a singleton instance of our LoggerService class. We can then instruct Nest to use the same singleton instance of LoggerService with the following construction:`

**Comment by Genbel** [comment]
Also fighting with the same issue, is there any solution?

**Comment by pkimtani** [comment]
I could get around this by adding `Logger` to the `providers` array of `task.module.ts`. Even though according README, adding to `providers` of `app.module.ts` should suffice, I am not sure why this weird behaviour. I infact ended up removing `Logger` from the providers array of my `app.module.ts`

P.S.: I am new to NestJS ecosystem and still trying to understand.

**Comment by Zyles** [comment]
> this might help - https://medium.com/@dvirarad/nestjs-custom-logger-with-rabbitmq-injection-da2f40ccddbd

That uses another way by wrapping the entire logging functionality. If I need to do that I don't need to use this package.

I want to do it this way as per documentation: https://github.com/gremo/nest-winston#replacing-the-nest-logger-also-for-bootstrapping but this is not working as documented.

**Comment by Zyles** [comment]
I also tried using the AppModule:

```
import {
  WinstonModule,
  utilities as nestWinstonModuleUtilities,
} from 'nest-winston'
import winston from 'winston'

// Winston logging transports
const transports = [
  new winston.transports.Console({
    format: winston.format.combine(
      winston.format.timestamp(),
      winston.format.colorize(),
      nestWinstonModuleUtilities.format.nestLike(),
    ),
  }),

  new winston.transports.File({
    filename: 'logs/error.log',
    level: 'error',
  }),

  new winston.transports.File({
    filename: 'logs/warn.log',
    level: 'warn',
  }),

  new winston.transports.File({
    filename: 'logs/info.log',
    level: 'info',
  }),

  new winston.transports.File({
    filename: 'logs/debug.log',
    level: 'debug',
  }),
]

WinstonModule.forRootAsync({
      useFactory: async () => ({
        // options
        transports: transports,
      }),
      inject: [],
    }),
```

Error:
`TypeError: Cannot read property 'combine' of undefined`

Is there a full working example somewhere? The docs are not very helpful.

**Comment by gremo** [comment]
@Zyles try using `import * as winston from 'winston'`, the error is about `combine` which is a function of winston package.

**Comment by gremo** [comment]
Feel free to comment if you still have this kind of problem, look for my answer ^^^^ above ^^^^, thanks.

**Comment by falahati** [comment]
this doesn't seem fixed. why is this issue closed then?
