### ISSUE TITLE
Log file does not been created by using WinstonModule.createLogger

### ISSUE THREAD

**Issue by charlesxsh** [gremo/nest-winston#386]
node: 16.1.0
winston: 3.3.3
nest-winston: 1.5.0
os: mac

```ts
import { WinstonModule } from 'nest-winston';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: WinstonModule.createLogger({
			transporters: [
          new winston.transports.File({ filename: 'abc.log' })
			]
    })
  });
}
bootstrap();
```

abc.log does not get created by using WinstonModule.createLogger way. The log file will be properly created if using original (winston) createLogger.

**Comment by gremo** [comment]
Closing this because it's not related to the library (`winston.transports.File` is from **winston** package).

Thanks for understanding 👍
