### ISSUE TITLE
Allow for `WinstonLogger` to be extensible

### ISSUE THREAD

**Issue by hjpotter92** [gremo/nest-winston#443]
Currently, the constructor defines a `private readonly logger` property, making its child class declaration nearly impossible. (https://github.com/gremo/nest-winston/blob/master/src/winston.classes.ts#L8).

Perhaps, having the logger property as protected would allow others to maybe able to expand the base class?

I am not sure if this is already possible, but I could not find anything relevant in the docs, hence the issue/thread.

**Comment by gremo** [comment]
I'm sorry for the very late response, I'm quite busy recently with my personal and working life. I'll try to follow more this library that, honestly, went so far and has been used by many. Didn't expected that 😄 

Anyways, should we do this? What about BC? I don't know but making that field `protected` seems wrong to me. Can you provide an example of a custom implementation and advances?
