### ISSUE TITLE
in async Promise.then() use this.logger is undefined

### ISSUE THREAD

**Issue by vichbb** [gremo/nest-winston#447]
in async Promise.then() use this.logger is undefined

**Comment by vichbb** [comment]
Hello, may I fail to pass:
method1: @Inject(Logger) private readonly logger: LoggerService
method2: constructor(private readonly logger: Logger) {}
Can I directly call the method in the Logger class to print the log?
Logger.log('message','contextInfo')

**Comment by gremo** [comment]
I'm sorry for the very late response, I'm quite busy recently with my personal and working life. I'll try to follow more this library that, honestly, went so far and has been used by many. Didn't expected that 😄 

There is no enough information here to understand the issue. I'll close it, feel free to reply further if it's not resolved for you.
