### ISSUE TITLE
Export nest like log format

### ISSUE THREAD

**Issue by kierans** [gremo/nest-winston#45]
I actually got this idea from https://github.com/pay-k/nestjs-winston (as an aside I don't know why this module/repo exists as it's not a fork of this repo and according the npm this module was published first, so it looks like the author just took a dump of this repo)

It's a Winston formatter that mimics the output format of the default Nest Logger.

```javascript
const nestLikeFormat = winston.format.printf(({ context, level, timestamp, message }) => {
  return `${level}: ${new Date(timestamp).toLocaleString()}\t [${colors.yellow(context)}] ${message}`;
});

const nestFormat = winston.format.combine(
  winston.format.timestamp(),
  winston.format.colorize({ all: true }),
  nestLikeFormat
);
```

**Comment by gremo** [comment]
Hi, thanks for the input. Can you explain me why I should use the formatter? Can you post a screenshot?

**Comment by cloud-down** [comment]
I was this formatter that lead to my example in #44, but here it is again (note the colours on the console are the same as what the Nest Logger uses)

```
info: 9/28/2019, 5:24:14 PM	 [InstanceLoader] TypeOrmCoreModule dependencies initialized
info: 9/28/2019, 5:24:14 PM	 [RoutesResolver] AppController {/}:
```

**Comment by kierans** [comment]
It was this format that lead to my example in #44, but here it is again (note the colours on the console are the same as what the Nest Logger uses)

```
info: 9/28/2019, 5:24:14 PM	 [InstanceLoader] TypeOrmCoreModule dependencies initialized
info: 9/28/2019, 5:24:14 PM	 [RoutesResolver] AppController {/}:
```

**Comment by danshapir** [comment]
The payk repo is actually the one that this author stole 99% of the code from... This repo only had an export module before my repo. Just look at the PRs.

**Comment by gremo** [comment]
Your created the repo just 26 days ago. What you are saying is a no-sense 😂

**Comment by danshapir** [comment]
Check the pull requests, all the functionality in this repo was literally written by me 🤣🤣

**Comment by gremo** [comment]
@danshapir yes, *that* functionality, not the entire project.... i did not stolen anything. You cloned my repo and do you things, which is perfectly right.... this is open source code. So you should really stop saying "stole".

**Comment by kierans** [comment]
I think the problem is that the fork link between this repo and https://github.com/pay-k/nestjs-winston is broken (assuming one was present in the first place) so when someone new comes alone it's easy to get confused. There's also no point having multiple copies of the same module in the npm registry IMHO.

![Screen Shot 2019-10-14 at 9 20 20 pm](https://user-images.githubusercontent.com/1179247/66744680-ca838e80-eec8-11e9-99c8-3ff74b62a83e.png)

I also don't think it's fair to claim @gremo stole anything. Firstly the license is MIT, so noone can actually steal anything. Secondly the merge commits show that the code was donated/merged in willingly https://github.com/gremo/nest-winston/pull/36

**Comment by danshapir** [comment]
@gremo I wish this was true. The last PR I closed and deleted, but still you went on and took my code...

And taking the code from this issue will do the same again. Copy paste...

**Comment by gremo** [comment]
@danshapir Again, I did not stolen anything. You contributed to this project as well as other people of this community. Thanks god, we still write open source code and the verb "stole" is completely inappropriate.

I was happy with your contribution but you were not able to respect the coding standard of this project and for this reason I authored that commit by myself.

Feel free to contribute again but without making a real mess with your commits. There is a file called `tslint.json` for this purpose. If you don't want to respect the rules, or you want to create a commit with your phone instead of using VSCode, then we can stop talking about this right now.

@kierans Can you make a PR with the code coming from @danshapir ?

**Comment by danshapir** [comment]
@kierans there are other stolen PRs.

Just like the comment above me asking you to make a PR with code coming from my repo 🤣

Common, I'm actually keeping my repo updated all the time, adding functionality and features. 

Just use it instead on copying stuff from it 😏 the more updated and well kept repo should survive.

**Comment by kierans** [comment]
@danshapir I understand your point that you may not have agreed to have code that you've written added to this repository However both your repos are licensed under the [MIT](https://opensource.org/licenses/MIT) license. Therefore @gremo cannot, and has not "stolen" anything, so it's inappropriate for you to say so. If you wish your intellectual property to remain your own, you need to have a less permissive license on your code. Looking at the commit history it's also easy to see your name on commits so attribution is present.

**Comment by kierans** [comment]
Personally I think everybody suffers from this type of split. What let me to this repo, is that @gremo has the `nestjs-winston` npm package and I was trying to figure out what the difference between it and `@payk/nestjs-winston` was.

What would be better is if somehow all code could be merged into one package and published.

**Comment by gremo** [comment]
This conversation is ridiculous. This is a small library with a few stars (30 or so) and downloads. There no reason to complain about the intellectual property of your work.

@danshapir there are no "other PRs", the only one I changed was #36 because you were NOT able to simply lint your code, even after i told you to do so. You are not able to collaborate with other people and do something for the community, for free.

@kierans I will work to port the new formatter from @danshapir repository.

**Comment by kierans** [comment]
> @kierans I will work to port the new formatter from @danshapir repository.

Thanks. I don't have the time currently.

**Comment by gremo** [comment]
@kierans what do you think? Last 4 lines are the custom nest-like formatter I'm writing:

![Cattura](https://user-images.githubusercontent.com/1532616/67891165-57c61480-fb52-11e9-81e0-69d598107a72.PNG)
