### ISSUE TITLE
I would like to add Morgan to my nest-winston stream to log HTTP Requests, but am unable to access it.

### ISSUE THREAD

**Issue by Alfagun74** [gremo/nest-winston#454]
I would like to add Morgan to my nest-winston stream to log HTTP Requests, but am unable to access it.
The following Stackoverflow Answer shows exactly what i want to do but i cant access the winston stream. 😢 

https://stackoverflow.com/a/28824464/14570696

Is there any way to make this more extendible so i can use the underlying Winston like im used to?

**Comment by Alfagun74** [comment]
Workaround:
`const logger = WinstonModule.createLogger({
  exitOnError: false,
  transports: transports,
  handleExceptions: true,
});

const stream = {
  write: function (message) {
    logger.log(message);
  },
};

const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    logger: winston,
  });
app.use(morgan("tiny", { stream: stream }));
`

**Comment by gremo** [comment]
I'm sorry for the very late response, I'm quite busy recently with my personal and working life. I'll try to follow more this library that, honestly, went so far and has been used by many. Didn't expected that 😄 

Anyways it seems a good solution IMHO. Glad that you have solved it, going to close this, feel free to reply.
