### ISSUE TITLE
Replace cli-color to chalk

### ISSUE THREAD

**Issue by fjodor-rybakov** [gremo/nest-winston#458]
Please replace `cli-color` to `chalk`, because `cli-color` depends on the `ec5-ext` package, which contains a malicious script https://github.com/medikoo/es5-ext/blob/main/package.json#L115

**Comment by gremo** [comment]
Can you make a PR?

**Comment by fjodor-rybakov** [comment]
> Can you make a PR?

fjodor-rybakov:feature/replace-to-chalk
