### ISSUE TITLE
Help wanted: fix GitHub actions (Renovate bot doesn't work anymore, dependencies outdated)

### ISSUE THREAD

**Issue by gremo** [gremo/nest-winston#475]
Hi folks! I need an help with [GitHub actions](https://github.com/gremo/nest-winston/actions): there is something wrong with the `npm install command`. All tests are failing and Renovate bot will not updated project dependencies since... months. 

@ubudragon @TrejGun 

> Run npm install @nestjs/common@$NEST_VERSION @nestjs/core@$NEST_VERSION @nestjs/testing@$NEST_VERSION
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: nest-winston@1.[6](https://github.com/gremo/nest-winston/runs/6397763343?check_suite_focus=true#step:3:6).2
> npm ERR! Found: rxjs@[7](https://github.com/gremo/nest-winston/runs/6397763343?check_suite_focus=true#step:3:7).4.0
> npm ERR! node_modules/rxjs
> npm ERR!   dev rxjs@"7.4.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer rxjs@"^6.0.0" from @nestjs/common@7.6.1[8](https://github.com/gremo/nest-winston/runs/6397763343?check_suite_focus=true#step:3:8)
> npm ERR! node_modules/@nestjs/common
> npm ERR!   dev @nestjs/common@"^7" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/runner/.npm/_logs/2022-05-[12](https://github.com/gremo/nest-winston/runs/6397763343?check_suite_focus=true#step:3:12)T00_04_[15](https://github.com/gremo/nest-winston/runs/6397763343?check_suite_focus=true#step:3:15)_470Z-debug-0.log

**Comment by faithfulojebiyi** [comment]
it seems to be a legacy dependency issue
caa you try it with --legacy-peer-deps @yourpackgename
