### ISSUE TITLE
nest-winston v1.6.3 has runtime error ERR_REQUIRE_ESM 

### ISSUE THREAD

**Issue by rbonestell** [gremo/nest-winston#531]
Unfortunately, it appears the 1.6.3 release introduced a dependency on Chalk v5: https://github.com/gremo/nest-winston/compare/v1.6.2...v1.6.3diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R24

From this pull request: https://github.com/gremo/nest-winston/commit/4be39e2d2977eaa812de746e7a9e78048a1c4fff

This has resulted in a runtime error in my project's use of NestJS:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/project/node_modules/nest-winston/node_modules/chalk/source/index.js from /path/to/project/node_modules/nest-winston/dist/winston.utilities.js not supported.
Instead change the require of index.js in /path/to/project/node_modules/nest-winston/dist/winston.utilities.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/path/to/project/node_modules/nest-winston/dist/winston.utilities.js:18:33)
```

The rest of the NestJS framework dependencies seem to use Chalk v4.
The latest version of Chalk v4 is [4.1.2](https://github.com/chalk/chalk/releases/tag/v4.1.2), perhaps this is the best version to target.

**Comment by gremo** [comment]
Are you able to downgrade to chalk@4? I think it’s the only way to ho.

**Comment by gremo** [comment]
We could also remove the dependecy I think: https://github.com/nestjs/nest/blob/master/packages/common/utils/cli-colors.util.ts

WDYT

**Comment by zhonggithub** [comment]
same issue

**Comment by lwhiteley** [comment]
same issue

```bash
For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

   /node_modules/.pnpm/chalk@5.0.1/node_modules/chalk/source/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import ansiStyles from '#ansi-styles';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/.pnpm/jest-runtime@27.5.1/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../node_modules/.pnpm/nest-winston@1.6.3_xi77xy5t5f67nxxivjlejge6yy/node_modules/nest-winston/dist/winston.utilities.js:18:33)
```

**Comment by lwhiteley** [comment]
just an FYI:
ive ran into this issue before and just replaced chlak with 
https://www.npmjs.com/package/ansi-colors

**Comment by gremo** [comment]
I'll try to remove it ASAP. I don't even know why I used a library in the first place, for just like.. 4 colors. In the meanwhile I'll deprecate 1.6.3

**Comment by gremo** [comment]
Can you test the master version with chalk removed? @lwhiteley @rbonestell

**Comment by lwhiteley** [comment]
Awesome, works for me! 👍🏾

**Comment by rbonestell** [comment]
Works great! Thanks for the quick fix @gremo!

**Comment by gremo** [comment]
You're welcome @rbonestell ! I'm sorry to have published a broken release but I almost forgot about that PR with the major chalk upgrade. Plus that code isnt' tested, feel free to collaborate further 👍
