### ISSUE TITLE
"Unknown logger level" error when used for bootstraping

### ISSUE THREAD

**Issue by rivatove** [gremo/nest-winston#599]
Hi, using the logger for bootstraping results in errors like this one:
`[winston] Unknown logger level: Nest application successfully started`

During bootstrap, nestjs calls logger's _log_ method with no argument for the level, e.g.:
`this.logger.log(constants_1.MESSAGES.APPLICATION_READY);`

And, since LoggerService method signature uses _any_, it accepts the interface and compilies despite the missing argument. 
`log(message: any, ...optionalParams: any[]): any;`

**Comment by i7N3** [comment]
Try this: [Replacing the Nest logger (also for bootstrapping)](https://github.com/gremo/nest-winston#replacing-the-nest-logger-also-for-bootstrapping)

**Comment by carefreelife98** [comment]
It seems that main.ts might be causing the issue.

```typescript
// it may cause the issue:
app.useLogger(app.get(WINSTON_MODULE_PROVIDER));

// you should change injection token to "WINSTON_MODULE_NEST_PROVIDER"
app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));
```
