### ISSUE TITLE
Nest can't resolve dependencies

### ISSUE THREAD

**Issue by iamjaredwalters** [gremo/nest-winston#602]
### Description

Following the docs to for [replacing the Nest logger (also for bootstrapping)](https://github.com/gremo/nest-winston#replacing-the-nest-logger-also-for-bootstrapping) I've configured the logger in `main.ts` using the following: 

```javascript
async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    // Override the default logger
    logger: WinstonModule.createLogger({
      instance: createLogger({
        level: process.env.LOG_LEVEL || 'info',
        transports: [
          new winston.transports.Console({
            format: logFormat(),
          }),
        ],
      }),
    }),
  })
}
``` 

I then provide the logger via my main module:
```javascript
@Module({
  imports: [IdentityModule],
  controllers: [],
  providers: [Logger],
})
```

And finally, type hint in a service:
```javascript
@Injectable()
export class IdentityService {
  constructor(
    private readonly logger: Logger,
  ) {}
}  
```

Nest then throws an exception `Error: Nest can't resolve dependencies of the IdentityService...`.

Any ideas how I can get dependency injection to work and also replace the logger during bootstrap?

**Comment by iamjaredwalters** [comment]
I can add the logger as a provider to each module that uses it but the docs claim I don't need this step. Am I misunderstanding them?

**Comment by karolchmiel94** [comment]
I had the same issue as you. Make sure that you're not setting logger again with
`app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));`

**Comment by lijing-2008** [comment]
> I had the same issue as you. Make sure that you're not setting logger again with `app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));`

I had the same isue as above without setting logger again with app.useLogger as you say. Have you fixed it?

**Comment by ngoduongkha** [comment]
I had the same issue when using `Logger` in LoggerMiddleware (import from `@nestjs/common`). Have you had any solution?

**Comment by riccardo-ditosto-gellify** [comment]
I'm also facing the same issue. Was anyone able to solve this?

**Comment by pengzitong** [comment]
如果你在app模块定义了下面的providers，
@Module({
  imports: [IdentityModule],
  controllers: [],
  providers: [Logger],
})
那么只能在app模块中使用logger，如果需要在其他模块中使用的话，需要在其他模块的provider中添加Logger，或者将app模块变成全局。

**Comment by pengzitong** [comment]
如果你在app模块定义了下面的providers，
```
@module({
    imports: [IdentityModule],
    controllers: [],
    providers: [Logger],
})
```
那么只能在app模块中使用logger，如果需要在其他模块中使用的话，需要在其他模块的provider中添加Logger，或者将app模块变成全局。

**Comment by johnkoehn** [comment]
Could we at the very least update documentation around this?
