### ISSUE TITLE
Is there a way to create a child logger?

### ISSUE THREAD

**Issue by XiovV** [gremo/nest-winston#664]
In my controllers and services I have to log data such as the username of the person who is making the request for logging purposes. I do not know how to create a child logger using this library, which means that for each log I have to write this:
```javascript
this.logger.log({username: user.username}, 'some log message')
```
This gets quite repetitive pretty quickly so I'd like to create a child logger instead, so I don't have to repeat this every time I want to log something, but I cannot find a way to create a child logger with this library. Thank you for your help.

**Comment by gitSambhal** [comment]
@XiovV 
You can create the child logger as follows
```ts
const childLogger = this.logger.child({ username: user.username });
childLogger.log('some log message');
```
