### ISSUE TITLE
Question: How to use it in TypeOrmModule?

### ISSUE THREAD

**Issue by Zaynex** [gremo/nest-winston#67]
Hi, my question is how to use it in TypeOrmModule ?
Currently, db query didn't saved in log.
```

const config: TypeOrmModuleOptions = {
  type: 'mysql',
  host: db.host,
  port: db.port,
  password: db.password,
  username: db.user,
  database: db.database,
  entities: [__dirname + '/**/*.entity{.ts,.js}'],
  logging: true,
  logger: // ?? <---- what should I inject here ?
};

@Module({
  imports: [
    TypeOrmModule.forRoot(config),
    UserModule,
    RoomModule,
    RoomHistoryModule,
    WinstonModule.forRoot({
      transports: [
        new winston.transports.Console({
          format: winston.format.combine(
            winston.format.timestamp({
              format: 'YYYY-MM-DD HH:mm:ss',
            }),
          ),
        }),
        dailyRotateFile,
        // other transports...
      ],
    }),
  ],
  controllers: [],
  providers: [
    {
      provide: APP_GUARD,
      useClass: AuthGuard,
    },
  ],
})
export class AppModule {}
```

**Comment by Zaynex** [comment]
Solve it by myself.

read  nestjs/nest#1300

**Comment by NoahMarconi** [comment]
@Zaynex do you have an example of what you did?

I'm using the bootsrapping setup and am not seeing how to connect that to typeorm: https://github.com/gremo/nest-winston#use-as-the-main-nest-logger-also-for-bootstrapping

**Comment by Zaynex** [comment]
> @Zaynex do you have an example of what you did?
> 
> I'm using the bootsrapping setup and am not seeing how to connect that to typeorm: https://github.com/gremo/nest-winston#use-as-the-main-nest-logger-also-for-bootstrapping

https://github.com/Zaynex/nestjs-demo
