### ISSUE TITLE
How can I pass json attributes into the logger?

### ISSUE THREAD

**Issue by cgvalayev** [gremo/nest-winston#676]
I am trying to achieve the following:

```js
// without error
this.logger.error('My error message', error, {
  a: 1,
  b: 2
});
// with error
this.logger.error('My error message', {
  a: 1,
  b: 2
});
```

but when i format using winston, second parameter is always stack and third is always context which is not ideal because i need the whole error and context, so where should custom attributes go?

Any suggestion?

**Comment by gm50x** [comment]
Hey! What I usually do to provide extra data into my logs is using json as the first argument, with a "message" key, which shows up as the object keys.

Example:
![image](https://github.com/gremo/nest-winston/assets/23168091/c65b9cda-ebac-4538-9b34-819ede22cfff)


Log output in "pretty" format:
![image](https://github.com/gremo/nest-winston/assets/23168091/e70fc1e4-2b6a-43f1-9a4f-2ae1e7837fb0)


Log output in json format:
![image](https://github.com/gremo/nest-winston/assets/23168091/fd68ba8f-83f0-48bb-91c6-99208183fd2b)


Here is how I configure my logger:
In main i use bufferLogs: true; Then I call app.useLogger with the provided logger configuration (which is basecally two formats one colored for local, one with no colors for centralized log infrastructured that runs in cloud environment.

![image](https://github.com/gremo/nest-winston/assets/23168091/6a72b372-913a-4226-8b88-49a91ad01bcc)
![image](https://github.com/gremo/nest-winston/assets/23168091/2d0caf29-1fc1-499f-93d6-b0d7b22d0b05)

**Comment by cgvalayev** [comment]
Thank you for sharing this @gm50x! Ill give it a try

**Comment by gremo** [comment]
You may have solved it, so let's close. Feel free to comment.
