### ISSUE TITLE
[Question]: Should documentation be updated?

### ISSUE THREAD

**Issue by inferusvv** [gremo/nest-winston#691]
### Description

I've picked "Replacing the Nest logger (also for bootstrapping)" to setup logger.

In the end of section there are 2 requirements:

1. Add `Logger` to `AppModule` providers.
2.  Inject in class constructor:

```typescript
import { Controller, Logger } from '@nestjs/common';

@Controller('cats')
export class CatsController {
  constructor(private readonly logger: Logger) {}
}
```

But as a result I am getting next error:

> Error: Nest can't resolve dependencies of the CatsController

After some investigation I found another way to use logger in class in official documentation [here](https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging).

```typescript
import { Logger, Injectable } from '@nestjs/common';

@Injectable()
class MyService {
  private readonly logger = new Logger(MyService.name);

  doSomething() {
    this.logger.log('Doing something...');
  }
}
```

And now everything is works. No need to add into providers list. So yeah.. Is it ok? Should documentation be updated?

**Comment by TroyMorvant** [comment]
> ### Description
> I've picked "Replacing the Nest logger (also for bootstrapping)" to setup logger.
> 
> In the end of section there are 2 requirements:
> 
> 1. Add `Logger` to `AppModule` providers.
> 2. Inject in class constructor:
> 
> ```ts
> import { Controller, Logger } from '@nestjs/common';
> 
> @Controller('cats')
> export class CatsController {
>   constructor(private readonly logger: Logger) {}
> }
> ```
> 
> But as a result I am getting next error:
> 
> > Error: Nest can't resolve dependencies of the CatsController
> 
> After some investigation I found another way to use logger in class in official documentation [here](https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging).
> 
> ```ts
> import { Logger, Injectable } from '@nestjs/common';
> 
> @Injectable()
> class MyService {
>   private readonly logger = new Logger(MyService.name);
> 
>   doSomething() {
>     this.logger.log('Doing something...');
>   }
> }
> ```
> 
> And now everything is works. No need to add into providers list. So yeah.. Is it ok? Should documentation be updated?

Wouldn't this just be using the built in nest logger and not the custom logger?

**Comment by inferusvv** [comment]
@TroyMorvant No, winston is used. All steps are taken from readme. 

I think secret is here:

```
  const app = await NestFactory.create(AppModule, {
    logger: WinstonModule.createLogger({
      // options (same as WinstonModule.forRoot() options)
    })
```

And then import from `@nestjs/common` should be used

**Comment by a1rwulf** [comment]
Same here.
```
private readonly logger = new Logger(MyService.name);
```
Seems to work instead of trying to put it in the constructor.

**Comment by bingyang519** [comment]
Solve it in another way

app.module.ts


@Global()    // important
@Module({
  providers: [Logger],
  exports: [Logger],  // important
  })
export class AppModule {}

**Comment by drewB** [comment]
I definitely think the documentation should be updated.   Since most people will be migrating from the default nest way of using the logger which is exactly the same the @inferusvv solution it is much less effort.

**Comment by compasss** [comment]
waste  a week to solve this problem
