### ISSUE TITLE
[Feature]: Support string-interpolation

### ISSUE THREAD

**Issue by yeongjet** [gremo/nest-winston#705]
### Description

[string-interpolation](https://github.com/winstonjs/winston#string-interpolation) is useful function in winston which conflicts with logger methods of nest-winston.
There are only two params in `log()`:
`log(message: any, context?: string)`
which can not use the string-interpolation like:
`log('teacher%o, doctor: %o', {name: "jack"}, {name: "wilson"})`

### Are you willing to contribute it?

- [ ] I can work on a pull request to implement this feature

**Comment by gremo** [comment]
Unfortunately the logger must implement https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts from Nest, so we can't change the log method signature.
