### ISSUE TITLE
[Feature]:  add fatal level 

### ISSUE THREAD

**Issue by mahmoudzeyada** [gremo/nest-winston#727]
### Description

Please include the "fatal" log level, which is a newly introduced level in the latest version of NestJS.

### Are you willing to contribute it?

- [ ] I can work on a pull request to implement this feature

**Comment by gremo** [comment]
This library supports a wide range of NextJS version. We can't add, at least now (without dropping support for old versions) this feature as it would break people code.

**Comment by gremo** [comment]
I'm open to a PR or suggestion, sure @mahmoudzeyada !

**Comment by mahmoudzeyada** [comment]
Cool will create pr in the weekend
