### ISSUE TITLE
[Question]:  processing optional arguments is not consistent with Nest

### ISSUE THREAD

**Issue by rovrevik** [gremo/nest-winston#805]
### Description

The nest logger implementation processes arguments from the end.
- .log/info/debug/warn all use the last argument as the context override.
- .error the last arguments are used as the stack and context override

In almost every case no one is using more than one/two optional arguments.
But the nest-winston logger deviates from the default nest implementation because it processes arguments from the beginning.

Given that the library is used in the wild and changing it could introduce unexpected output if changed.

Would updating the optional argument processing to make it (more) inline with nests console logger implementation be considered?

**Comment by rovrevik** [comment]
Are there any opinions on this?

**Comment by Alfagun74** [comment]
This is annoying me aswell, i just want the default message, ...optionalParams interface.

Context should **always** be fetched automatically.

**Comment by falahati** [comment]
can we even fix this manually? is there a workaround?

Although I think this is a problem that should be solved eventually (maybe with a new major version), for the time being, the addition of a new property to let us change the behavior could be useful.

The order of the `stack` and `context` is also wrong on the `error` callback. in other words it always considers the second argument as the context.
