### ISSUE TITLE
[Bug]: Code for v1.9.5 of Nest Winston not in NPM

### ISSUE THREAD

**Issue by WayneStilwell** [gremo/nest-winston#818]
### Version of Nest?

10.3.1

### Version of nest-winston package?

1.9.5

### Version of winston package?

3.11.0

### Bug description

Our CI tool is failing to pull `nest-winston`. It appears the code for the most recent release may not have made it to NPM: https://www.npmjs.com/package/nest-winston?activeTab=code

We've pinned version 1.9.4 in our `package.json` in the meantime.

**Comment by Segfaultd** [comment]
Same issue here. Went crazy, I was near reinstalling my complete setup because of missing dep. Until I figured out that the released version was empty.

**Comment by gremo** [comment]
Sorry the the mistake, going to solve It in a few minutes

**Comment by gremo** [comment]
Deprecated 1.9.5... new patch released.

**Comment by Segfaultd** [comment]
Thanks @gremo for the fast action!
