### ISSUE TITLE
Use winston functions

### ISSUE THREAD

**Issue by Themandunord** [gremo/nest-winston#86]
Hello Guys!

How do you do to call profiling function on this logger ? (https://github.com/winstonjs/winston#profiling), I need that for my project, but I cannot achieve it..

Do you have a solution?

Thank you

**Comment by gremo** [comment]
Hi, thanks for answering.

I think you can simply inject the logger in your service/controller: the logger is exactly what `createLogger` function returns (have a look [here](https://github.com/gremo/nest-winston/blob/master/src/winston.providers.ts#L38)). Then, call `startTimer()` on the logger itself.

Let me know.

**Comment by Themandunord** [comment]
Oh yeah, I see!

Thank you!
