### ISSUE TITLE
Can I use nest-winston with `express-winston` too?

### ISSUE THREAD

**Issue by reinoute** [gremo/nest-winston#98]
Can I use it with [express-winston](https://github.com/bithavoc/express-winston) too?

The reason I ask is that express-winston supports logging response body and supports logging to [Stackdriver/Google cloud](https://github.com/bithavoc/express-winston#stackdrivergoogle-cloud-logging).

**Comment by gremo** [comment]
I think it should be possibile.

Maybe creating a middleware (see https://docs.nestjs.com/middleware) injecting the same options we use for this module. Then, inside the middleware, specify thet the use function is that coming from `expressWinston.logger`?

Another possibility could be appling it globally... but you need to figure out how to get che module options (to be passed to  `expressWinston.logger` function).

```
const app = await NestFactory.create(AppModule);
app.use(expressWinston.logger());
await app.listen(3000);
```

Maybe @Piranit or @TrejGun could help?

**Comment by TrejGun** [comment]
you most likely can use `express-winston` without `nest-winston` as shown above 
and then write custom formatter

**Comment by gremo** [comment]
@TrejGun can you help here? Can be closed, right (out of scope of this package)?

**Comment by TrejGun** [comment]
i guess so)
what kind of help do you need? i dont have "close" button

**Comment by gremo** [comment]
@TrejGun yep you can't close, but I can. Should we close this issue because it's not actually related to nest-winston package?

**Comment by TrejGun** [comment]
i think so)

**Comment by gremo** [comment]
Thanks
