### ISSUE TITLE
Can I use this logger to see the logs of my project when it runs on a server?

### ISSUE THREAD

**Issue by Nikos-kun** [gremo/nest-winston#99]
Hello, I'm new with nestjs.

Description::
There is an outside of my network plugin that sends data to my nestjs that runs on a server.
And it seems my nestjs responds with: 

```status: 500
responseText: "{"statusCode":500,"message":"Internal server error"}"
success: false```

Can I use this logger to see what data I'm receiving from that plugin?
When I was working locally I was able to use the default logger for that, plus a simple console.log() and I could easily see the receiving objects.

But now that I'm online and that I have to receive something outside of my network I don't know where to see what my nestjs is receiving.

So my basic question:
Can I use this logger to see what I'm receiving while being live on a server?
And if yes, how? Is there a specific file that shows me logs?
Does it have a specific name or path?

**Comment by hamxabaig** [comment]
@Nikos-kun Even if you plug this logger into your nestjs project. It won't have any effect until you log manually in the code yourself using the logger.

You can also have a look at [Exception Filters](https://docs.nestjs.com/exception-filters) in NestJS.

**Comment by gremo** [comment]
@hamxabaig can I close this issue? @Nikos-kun is this resolved? Thanks

**Comment by hamxabaig** [comment]
@gremo Yeah sure, It doesn't seem to be `nest-winston` issue
